import type { Metadata } from 'next'

import { getBaseUrl } from './utils'

export const seo = (params: {
  title?: string
  description?: string
  images?: string[]
  url?: string
}): Metadata => {
  const siteName = 'Create Yuki App'
  const title = params.title ?? siteName
  const description = params.description ?? 'Generated by create yuki app'
  const images = [...(params.images ?? []), '/api/og']
  const url = params.url ? `${getBaseUrl()}${params.url}` : getBaseUrl()

  return {
    title,
    description,
    applicationName: siteName,
    openGraph: { images, url, siteName, type: 'website' },
    twitter: { card: 'summary_large_image' },
    alternates: { canonical: url },
    icons: { icon: 'https://tiesen.id.vn/favicon.ico' },
  }
}
